### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/python-quick-reaction-game#6]
Hi @lauraclay and @LornaLynch 
I've updated this resource so it now uses gpiozero.
My changes are on a different branch - gpiozero-update.
You can compare the two [here](https://github.com/raspberrypilearning/python-quick-reaction-game/compare/master...gpiozero-update?diff=split&name=gpiozero-update&short_path=5e12d1f#diff-5e12d1fe67e105431a216acadcab984a) with the additions being in green and deletions in red.
Let me know if there are any problems

Thanks

**Comment by LornaLynch** [comment]
If I make changes on the gpiozero-update branch, will that mess the merge up?

**Comment by LornaLynch** [comment]
I've done the pull request after making changes. Can you let me know if it worked from your end, @MarcScott? I'm having a GitHub crisis of confidence...

**Comment by MarcScott** [comment]
That's perfect @LornaLynch - all worked beautifully and updated on the site. Your GitHub skills are perfect. Thank you
